spring:
  profiles:
    active: h2
  datasource:
    url: jdbc:h2:mem:batch
    username: sa
    driver-class-name: org.h2.Driver

---

spring:
  profiles:
    active: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

---

spring:
  batch:
    job:
      names: ${job.name:NONE}
      # batch가 실행될때 Program arguments로 job.name 값이 넘어오면 해당 값과 일치하는 Job만 실행시키겠다는 설정
      # 만약 job.name이 할당되지 않았다면 NONE을 할당
      # NONE이 할당될 시 어떤 batch도 실행되지 않음.

      # job.name 할당 하는법: Run -> Edit Configuration, Program arguments에 --job.name="job.name명" 선언하여 할당하면 된다

      # 실제 운영환경 에서는 java -jar *.jar --job.name=simpleJob 과 같이 배치를 실행합니다 (*.jar는 해당 application의 jar파일을 뜻함)